//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        internal static string RS_ABOUT {
            get {
                return ResourceManager.GetString("RS_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система биллинга.
        /// </summary>
        internal static string RS_ABOUT_TEXT {
            get {
                return ResourceManager.GetString("RS_ABOUT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        internal static string RS_ADDRESS {
            get {
                return ResourceManager.GetString("RS_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответить.
        /// </summary>
        internal static string RS_ANSWER {
            get {
                return ResourceManager.GetString("RS_ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система биллинга.
        /// </summary>
        internal static string RS_APP_TITLE {
            get {
                return ResourceManager.GetString("RS_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авто.
        /// </summary>
        internal static string RS_AUTO {
            get {
                return ResourceManager.GetString("RS_AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс.
        /// </summary>
        internal static string RS_BALANCE {
            get {
                return ResourceManager.GetString("RS_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string RS_CANCEL {
            get {
                return ResourceManager.GetString("RS_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключение.
        /// </summary>
        internal static string RS_CONNECTION {
            get {
                return ResourceManager.GetString("RS_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата подключения.
        /// </summary>
        internal static string RS_CONNECTION_DATE {
            get {
                return ResourceManager.GetString("RS_CONNECTION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        internal static string RS_CREATE {
            get {
                return ResourceManager.GetString("RS_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string RS_DATE {
            get {
                return ResourceManager.GetString("RS_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string RS_DELETE {
            get {
                return ResourceManager.GetString("RS_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правка.
        /// </summary>
        internal static string RS_EDIT {
            get {
                return ResourceManager.GetString("RS_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        internal static string RS_EMAIL {
            get {
                return ResourceManager.GetString("RS_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string RS_FIRST_NAME {
            get {
                return ResourceManager.GetString("RS_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форум.
        /// </summary>
        internal static string RS_FORUM {
            get {
                return ResourceManager.GetString("RS_FORUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        internal static string RS_HOME {
            get {
                return ResourceManager.GetString("RS_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хостинг.
        /// </summary>
        internal static string RS_HOSTING {
            get {
                return ResourceManager.GetString("RS_HOSTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интернет заблокирован!!.
        /// </summary>
        internal static string RS_INTERNET_DISABLED {
            get {
                return ResourceManager.GetString("RS_INTERNET_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP-адрес.
        /// </summary>
        internal static string RS_IP {
            get {
                return ResourceManager.GetString("RS_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        internal static string RS_IS_ADMIN {
            get {
                return ResourceManager.GetString("RS_IS_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешен.
        /// </summary>
        internal static string RS_IS_ALLOW {
            get {
                return ResourceManager.GetString("RS_IS_ALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочтено.
        /// </summary>
        internal static string RS_IS_READED {
            get {
                return ResourceManager.GetString("RS_IS_READED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        internal static string RS_LAST_NAME {
            get {
                return ResourceManager.GetString("RS_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог.
        /// </summary>
        internal static string RS_LOG {
            get {
                return ResourceManager.GetString("RS_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string RS_LOGIN {
            get {
                return ResourceManager.GetString("RS_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о пользователе.
        /// </summary>
        internal static string RS_LOGIN_ACCOUNT_INFO {
            get {
                return ResourceManager.GetString("RS_LOGIN_ACCOUNT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя и пароль.
        /// </summary>
        internal static string RS_LOGIN_HELP {
            get {
                return ResourceManager.GetString("RS_LOGIN_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить.
        /// </summary>
        internal static string RS_LOGIN_REMEMBER_ME {
            get {
                return ResourceManager.GetString("RS_LOGIN_REMEMBER_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string RS_LOGOUT {
            get {
                return ResourceManager.GetString("RS_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщения.
        /// </summary>
        internal static string RS_MESSAGES {
            get {
                return ResourceManager.GetString("RS_MESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотреть.
        /// </summary>
        internal static string RS_MESSAGE_OPEN {
            get {
                return ResourceManager.GetString("RS_MESSAGE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        internal static string RS_MIDDLE_NAME {
            get {
                return ResourceManager.GetString("RS_MIDDLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости.
        /// </summary>
        internal static string RS_NEWS {
            get {
                return ResourceManager.GetString("RS_NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система управления биллингом. Нажмите &quot;Войти&quot; чтобы авторизоваться..
        /// </summary>
        internal static string RS_NOT_AUTORIZED_TEXT {
            get {
                return ResourceManager.GetString("RS_NOT_AUTORIZED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        internal static string RS_NUMBER {
            get {
                return ResourceManager.GetString("RS_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ок.
        /// </summary>
        internal static string RS_OK {
            get {
                return ResourceManager.GetString("RS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string RS_PASSWORD {
            get {
                return ResourceManager.GetString("RS_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распечатать квитанцию.
        /// </summary>
        internal static string RS_PRINT_QUITTANCE {
            get {
                return ResourceManager.GetString("RS_PRINT_QUITTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        internal static string RS_SEARCH {
            get {
                return ResourceManager.GetString("RS_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Послать.
        /// </summary>
        internal static string RS_SEND {
            get {
                return ResourceManager.GetString("RS_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тариф.
        /// </summary>
        internal static string RS_TARIFF {
            get {
                return ResourceManager.GetString("RS_TARIFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тарифы.
        /// </summary>
        internal static string RS_TARIFFS {
            get {
                return ResourceManager.GetString("RS_TARIFFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        internal static string RS_TEXT {
            get {
                return ResourceManager.GetString("RS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        internal static string RS_TITLE {
            get {
                return ResourceManager.GetString("RS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        internal static string RS_USER {
            get {
                return ResourceManager.GetString("RS_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        internal static string RS_USERNAME {
            get {
                return ResourceManager.GetString("RS_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        internal static string RS_USERS {
            get {
                return ResourceManager.GetString("RS_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От кого.
        /// </summary>
        internal static string RS_USER_FROM {
            get {
                return ResourceManager.GetString("RS_USER_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать.
        /// </summary>
        internal static string RS_WELCOME {
            get {
                return ResourceManager.GetString("RS_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написать администратору.
        /// </summary>
        internal static string RS_WRITE_TO_ADMIN {
            get {
                return ResourceManager.GetString("RS_WRITE_TO_ADMIN", resourceCulture);
            }
        }
    }
}
